name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        pip install -U pip
        pip install poetry

    - name: Install dependencies using Poetry
      run: |
        poetry config virtualenvs.create false
        poetry install

    - name: Run tests using Poetry
      run: |
        poetry run pytest tests/

    - name: Lint with flake8
      run: |
        poetry run flake8 ./file_organizer --exit-zero

    - name: Analyze code with pylint
      run: |
        poetry run pylint ./file_organizer

    - name: Scan for secrets with Gitleaks
      uses: zricethezav/gitleaks-action@v2

